### ISSUE TITLE
Allow deleting of podcasts

### ISSUE THREAD

**Issue by danieldiekmeier** [casualcoding/podcastprofile#2]
The Overcast OPML Export contains Podcasts I where I only listened to single episodes. It's Overcasts fault these are included at all, but completely deleting them from the profile would be nice.

**Comment by floriandotpy** [comment]
New release now removes hidden podcasts from the Settings screen. They are still accessible in a list of "hidden podcasts" though.

This has an advantage over completely deleting them: The next time you upload a new version of your OPML file, we keep the hidden podcasts hidden. If you had removed them, they would reappear in the visible list.

We might implement actual removing in the future, but for now we think this is the better solution.

**Comment by danieldiekmeier** [comment]
Yes, I agree. Great work!
